In [1]:
import numpy as np

In [2]:
a = [[1,2,3] ,[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
b = np.array(a)
print(b)
b.T

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
c = np.array([
    [3,5,7],
    [1,5,9],
    [1,2,3]
])
c

array([[3, 5, 7],
       [1, 5, 9],
       [1, 2, 3]])

In [ ]:
d = b.dot(c)
d

array([[  8,  21,  34],
       [ 23,  57,  91],
       [ 38,  93, 148]])

In [ ]:
b @ c

array([[  8,  21,  34],
       [ 23,  57,  91],
       [ 38,  93, 148]])

In [ ]:
f = np.where(d<10,d,d*10)