In [1]:
import numpy as np

In [2]:
# 深拷贝与浅拷贝问题
a =np.arange(0,15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
a[1:3]


array([1, 2])

In [4]:
a[1:3] = 9
a

array([ 0,  9,  9,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
# 浅拷贝
b = a[1:3]
b[:] = 999
b
a

array([  0, 999, 999,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [6]:
# 深拷贝
c = a[1:3].copy()
print(c)
print(a)
c[:] = 111
print(a)


[999 999]
[  0 999 999   3   4   5   6   7   8   9  10  11  12  13  14]
[  0 999 999   3   4   5   6   7   8   9  10  11  12  13  14]


In [ ]:
# 普通列表
a_m = [[1,2,3] ,[4,5,6],[7,8,9]]
# numpy矩阵
a_m = np.array([[1,2,3] ,[4,5,6],[7,8,9]]) 
a_m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 矩阵切片功能
# [x:y,n:m] 行[x,y),列[n,m)
a_m[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [68]:
a = np.zeros((10,10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])